services:
  - type: web
    name: gpt-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
	  - key: TELEGRAM_TOKEN
	    sync: false
	  - key: OPENAI_API_KEY
	    sync: false



